### ISSUE TITLE
Next does not terminate a function

### ISSUE THREAD

**Issue by halostatue** [sjinks/express-ip-filter-middleware#235]
https://github.com/sjinks/express-ip-filter-middleware/blob/master/src/index.ts#L63-L67

This:

```javascript
        if ((allowed && !denied) || (options.mode === 'blacklist' && (allowed || !denied))) {
            next();
        }

        next(new IPBlockedError('Access denied', ip));
```

Should be this:

```javascript
        if ((allowed && !denied) || (options.mode === 'blacklist' && (allowed || !denied))) {
            next();
        } else {
          next(new IPBlockedError('Access denied', ip));
        }
```

Otherwise, `next()` gets called twice. Depending on how everything else is being used, this does weird things. In my case (where I’m trying to apply an IP filter to a router), I am getting an error.

**Comment by sjinks** [comment]
Good eye! Thank you, fixed in 8688553.
